export const ConstituencyNames = new Map([
    [1,'Legnica'],
    [2, 'Wałbrzych'],
    [3, 'Wrocław'],
    [4, 'Bydgoszcz'],
    [5, 'Toruń'],
    [6, 'Lublin'],
    [7, 'Chełm'],
    [8, 'Zielona Góra'],
    [9, 'Łódź'],
    [10, 'Piotrków Trybunalski'],
    [11, 'Sieradz'],
    [12, 'Chrzanów'],
    [13, 'Kraków'],
    [14, 'Nowy Sącz'],
    [15, 'Tarnów'],
    [16, 'Płock'],
    [17, 'Radom'],
    [18, 'Siedlce'],
    [19, 'Warszawa'],
    [20, 'Warszawa II'],
    [21, 'Opole'],
    [22, 'Przemyśl'],
    [23, 'Rzeszów'],
    [24, 'Białystok'],
    [25, 'Gdańsk'],
    [26, 'Gdynia'],
    [27, 'Bielsko-Biała'],
    [28, 'Częstochowa'],
    [29, 'Gliwice'],
    [30, 'Rybnik'],
    [31, 'Katowice'],
    [32, 'Sosnowiec'],
    [33, 'Kielce'],
    [34, 'Elbląg'],
    [35, 'Olsztyn'],
    [36, 'Kalisz'],
    [37, 'Konin'],
    [38, 'Piła'],
    [39, 'Poznań'],
    [40, 'Koszalin'],
    [41, 'Szczecin']
])